### ISSUE TITLE
Unable to access user account screen

### ISSUE THREAD

**Issue by SilverSeraphim** [pydt/web#12]
![2017-11-06 13_31_20-play your damn turn](https://user-images.githubusercontent.com/406642/32459498-eb128956-c2fd-11e7-92e2-7bb2e0752ac7.png)

As an aside, it's very inconvenient that there's no way to turn off email notifications. I use the desktop app and a custom Discord bot, so emails are just legions of spam for me. I had thought deleting my email from the system would be the solution, but now I can't create or join games. And I can't put my email back in because of this bug. Seems like putting a fake email address is what I have to do, once I can get in.

Another note, I get the same error in Chrome (including incognito), and IE.

**Comment by mrosack** [comment]
I'm not going to have time to take a look at this today, but deleting your email address should work, so I'm not sure what happened here.  I'll try to get to it tomorrow, is SilverSeraphim your steam username?

**Comment by SilverSeraphim** [comment]
Yes, sir it is. Thanks for your quick response. Here's a screenshot of the error when I try to create or join.
![2017-11-06 15_16_25-play your damn turn](https://user-images.githubusercontent.com/406642/32461921-8aacb214-c305-11e7-9c3b-7b9650ecbd3e.png)

**Comment by mrosack** [comment]
It didn't have anything to do with the email address, it was a bug rendering some user info when the user had resigned from all their games.  I'm not going to remove the "No Notification Email Set" check for creating a game, as that's a bar to entry to try and keep down the number of people that would create a game and never come back to start it.

You can definitely add your email address, create the game, and remove your email address if you want, though.

Fixed in 5499cf000ded6e5f545b3b5bfb80b64e43b9e583

**Comment by SilverSeraphim** [comment]
Much appreciated. I'm able to access my account screen once again! Thanks for building a great site/app!
